### ISSUE TITLE
SC-4: The information system prevents unauthorized and unintended information transfer via shared system resources.

### ISSUE THREAD

**Issue by shawndwells** [RedHatGov/OpenShift-on-Azure#66]

**Comment by shawndwells** [comment]
"
![image](https://cloud.githubusercontent.com/assets/5713754/19585420/441941f4-971a-11e6-8c54-f247caee72a6.png)"

**Comment by rlucente-retro** [comment]
The Persistent Volumes within OpenShift must be configured to recycle the persistent volume once the claim is released.  If supported by the appropriate volume plugin, recycling performs a basic scrub (rm -rf /thevolume/*) on the volume to make it available again for a new claim.  In order to satisfy this control relative to storage, the underlying volume plugin must support recycling.

**Comment by enham** [comment]
By default, OpenShift has no restrictions for pod to pod communication. Project-based segmentation of network is supported but must be configured.

**Comment by enham** [comment]
Access to OpenShift metadata is limited by RBAC through the APIs but implementation of infrastructure-level access controls are delegated to the infrastructure provider. Also, several components in particular could be deployed on dedicated infrastructure to provide additional level of isolation include etcd (which stores all of the OpenShift cluster metadata), registry, and router.
